version: "3.6"
services:  
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
    # this ensures database is loaded first.
      - db  
    volumes:    
      - /app/node_modules
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${IMMO_DB_PASSWORD}
      POSTGRES_USER: ${IMMO_DB_USER}
      POSTGRES_DB: ${IMMO_DB}
    volumes:
      - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - data_db:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"  
volumes:
  data_db: